### ISSUE TITLE
DGEMM Failures on Fiji

### ISSUE THREAD

**Issue by FreddieWitherden** [clMathLibraries/clBLAS#267]
Compiling clBLAS and running `./test-short --gtest_filter=*dgemm*` on a Linux system with Catalyst 15.12 and an R9 Nano GPU results in a variety of test failures, as detailed below.

[test.txt](https://github.com/clMathLibraries/clBLAS/files/264079/test.txt)

clBLAS was compiled as: `cmake -G"Unix Makefiles" -DOPENCL_VERSION=2.0` followed by a make.

**Comment by kknox** [comment]
Looks like you are testing the /master branch at this point; /develop has fixes checked into it that have not been promoted yet.  Also, it is important to use MKL or [netlib blas](https://github.com/live-clones/lapack) as the reference library, because our unit tests expect bit precise ( O ULP ) results and we have had problems with both ACML and Atlas in the past.

[Arrayfire](http://arrayfire.com/) has kindly hosted a [clBLAS dashboard](http://ci.arrayfire.org/view/All/job/clMathLibraries/) for develop branch, and we currently have green lights for AMD platforms.

**Comment by FreddieWitherden** [comment]
I can confirm that switching from the master branch to the develop branch resolves these issues.
