### ISSUE TITLE
Requested OpenCL version: 1.2, Found OpenCL version 0.0

### ISSUE THREAD

**Issue by jrgruher** [clMathLibraries/clBLAS#331]
Hi, wondering if anyone can provide some guidance.  I'm on Ubuntu 14.04.  I've pulled down clBLAS from git and am attempting cMake.

root@donfpga2:/home/don/clBLAS/src/build# cmake ..
-- You have confirmed OpenCL 1.2 is supported in your system
-- CORR_TEST_WITH_ACML set to OFF. Try link with libblas.so
-- Target platform: 64-bit
-- Using default OpenCL Compiler
-- OPENCL_INCLUDE_DIRS: /usr/include
-- FindOpenCL searching for 64-bit libraries
CMake Error at FindOpenCL.cmake:143 (message):
  Requested OpenCL version: 1.2, Found OpenCL version: 0.0
Call Stack (most recent call first):
  CMakeLists.txt:278 (find_package)

I have installed the Intel OpenCL driver/runtime and SDK so I'm not sure why this is failing.  Any tips on how I should be setting up OpenCL for this to work or how I might debug further?  Thanks!

**Comment by tmagomedov** [comment]
src/FindOpenCL.cmake CMake script is used to find OpenCL. It looks for the cl.h header and greps it for CL_VERSION_1_1, CL_VERSION_1_2, CL_VERSION_2_0.  This points him to OpenCL version supportred by header. On my system I have the following code in cl.h for example:
``` 194 /* OpenCL Version */
 195 #define CL_VERSION_1_0                              1
 196 #define CL_VERSION_1_1                              1
 197 #define CL_VERSION_1_2                              1
 198 #define CL_VERSION_2_0                              1
```
You can try to set `set( OpenCL_VERSION "0.0" )` line to `set( OpenCL_VERSION "1.2" )` if you are sure. Or better check what particular cl.h header is found and what CL_VERSION_X_X are defined in it.

**Comment by jrgruher** [comment]
Thanks for the response.  I do have cl.h header on my system.  How does it know where to look for cl.h, is it guided by some environment variable?  I wonder if I just need to configure or fix some environment variable and then it will work.

By the way, what OpenCL package/distribution do you test against?

Thanks!

don@donfpga2:~$ cat /opt/intel/opencl-1.2-6.4.0.25/SDK/include/CL/cl.h|grep CL_VERSION
#define CL_VERSION_1_0                              1
#define CL_VERSION_1_1                              1
#define CL_VERSION_1_2                              1

**Comment by tmagomedov** [comment]
You can check `OPENCL_INCLUDE_DIRS` variable in your CMakeCache.txt. If it is not `/opt/intel/opencl-1.2-6.4.0.25/SDK/include` you can try pointing clBLAS to it by using `OPENCL_ROOT` CMake variable like this:
```
cmake ../src/ -DOPENCL_ROOT=/opt/intel/opencl-1.2-6.4.0.25/SDK
```
And yes, it also checks environment variables `OPENCL_ROOT`, `AMDAPPSDKROOT` and `CUDA_PATH`.
Newer versions of FindOpenCL.cmake script found in CMake distribution look at `INTELOCLSDKROOT` variable too but it doesn't matter really since every vendor supports ICD in their implementation. Headers are almost the same in all SDK's and there is no difference what libOpenCL.so to link with. I personally use headers from opencl-headers package which are in `/usr/include/CL`.

**Comment by jrgruher** [comment]
Thanks!  Settings the OPENCL_ROOT environment variable (and cleaning up the files in the build directory from my previous failed attempts) allowed the build to complete.
